### ISSUE TITLE
actividad 4 mapa mental comunicacion oral y escrita

### ISSUE THREAD

**Issue by ARICELCASTRO1999** [SistemasTecTlaxiaco/actividad-4-mapa-mental-ARICELCASTRO1999#1]
[ilovepdf_pages-to-jpg (2).zip](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-ARICELCASTRO1999/files/9639561/ilovepdf_pages-to-jpg.2.zip)

**Comment by 11042002** [comment]
Tu calificación es de: 18.5%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
